### ISSUE TITLE
[Bug] Unable to close terminal tab when there is terminal error

### ISSUE THREAD

**Issue by kimlisa** [gravitational/webapps#250]
#### Reproduce
This was how i encountered the error, sure there are other ways:

Set `require_session_mfa` on:
```
authentication:
    type: local
    second_factor: optional
    require_session_mfa: yes
```
There is currently an error with chrome on how `require session mfa` feature works in UI, and this results in timing out error. After 30 seconds, trying to exit out won't allow you to b/c numUsers is undefined: https://github.com/gravitational/webapps/blob/master/packages/teleport/src/Console/useOnExitConfirmation.ts#L73
